# Generated by Django 3.0.5 on 2023-08-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seesion_Year',
            new_name='Session_Year',
        ),
    ]
